### PR TITLE
Remove trilead from credentials test

### PR DESCRIPTION
**Pull request by timja**
Fixes the current test failure on https://github.com/jenkinsci/bom/pull/110

Could we please get a release so that we can incorporate it into the bom

### CODE REVIEW

**Comment by timja** [comment]
@jvz any chance you could ping someone internally to merge / release this please? 😄

**Comment by jvz** [comment]
@jeffret-b or @Wadeck can we get this merged and released?

**Comment by timja** [comment]
@jglick ping :)

**Comment by jeffret-b** [comment]
I've filed an infra ticket to get the GH permissions lined up with the repository-permissions-updater so I can release. Haven't back on the infra ticket yet.

**Comment by timja** [comment]
Ticket number?

**Comment by jeffret-b** [comment]
[INFRA-2450](https://issues.jenkins-ci.org/projects/INFRA/issues/INFRA-2450)

**Comment by timja** [comment]
Nudged in IRC

**Comment by jglick** [comment]
released as 1.6

**Comment by jeffret-b** [comment]
Thanks Jesse!

**Pull request merged**
